---
new_ticket:
  title: Nuevo Ticket
  content: >
    Activalo si esparas que una respuesta automatica sea enviada al usuario al crear un nuevo ticket.
  links:
    - 
      title: Nueva plantilla para autorespuesta del ticket.
      href: /scp/templates.php?default_for=ticket.autoresp
new_ticket_by_staff:
  title: Nuevo ticket por el personal
  content: >
    Aviso enviado cuando un agente crea una entrada en nombre del usuario. <em>Agente esto puede reemplazar al crear nuevas entradas.</em>
  links:
    - 
      title: Nueva plantilla de aviso de boleto
      href: /scp/templates.php?default_for=ticket.notice
new_message_for_submitter:
  title: Confirmación de Nuevo Mensaje
  content: >
    Aviso de confirmación enviado cuando un nuevo mensaje se anexa a una entrada existente.
  links:
    - 
      title: Nueva plantilla de mensaje de confirmación
      href: /scp/templates.php?default_for=message.autoresp
new_message_for_participants:
  title: Nueva notificación de mensaje
  content: >
    Difusión de los mensajes recibidos del remitente del mensaje a todos los demás participantes en el Ticket.
  links:
    - 
      title: Nueva plantilla de aviso de actividad
      href: /scp/templates.php?default_for=ticket.activity.notice
overlimit_notice:
  title: Aviso de limite sobrepasado
  content: >
    Billete negó aviso enviado al usuario sobre la violación de la <span class="doc-desc-title"> Máxima apertura de Tickets</span>.
  links:
    - 
      title: Plantilla de aviso de sobregiro
      href: /scp/templates.php?default_for=ticket.overlimit
    - 
      title: Establecer la <em>máxima apertura de Tickets</em>
      href: /scp/settings.php?t=tickets
